# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7df2feb56c4c518ebfa10b33707e9e9a5a23102f1958caea3084d4f9583d7c0e58b3b580c39f9ac9f84b9743a1139e09391fe6c8b7473dccae55dac555f422ac

test:
  secret_key_base: fd070d1d4a95574a38b5d4fc8b1f69ca4d840e18f52ca07aaec10339060d980c005aabee6fe64669f433b1c84643dd14a3de1ac3aa21f4cef56f407c74d1eae0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
